site_name: PiNN Documentation
nav:
  - Home:
      - Introduction: index.md
      - Migration to PiNN 1.x: migration.md
      - Changelog: changelog.md
  - Usage:
      - Overview: usage/overview.md
      - Quick Start: usage/quick_start.md
      - CLI:
          - convert: usage/cli/convert.md
          - train: usage/cli/train.md
          - log: usage/cli/log.md
      - Datasets: usage/datasets.md
      - Networks:
          - Overview: usage/networks.md
          - PiNet: usage/pinet.md
          - BPNN: usage/bpnn.md
      - Models:
          - Overview: usage/models.md
          - Potential Model: usage/potential.md
          - Dipole Model: usage/dipole.md
          - Custom Mdoel: usage/custom_model.md
      - Optimizers: usage/optimizers.md
      - Visualize: usage/visualize.md
  - Notebooks:
      - Overview: notebooks/overview.md
      - Tutorials:
          - Quick Start: notebooks/Quick_tour.ipynb
          - Training Tips: notebooks/More_on_training.ipynb
      - Examples:
          - Custom Dataset: notebooks/Customizing_dataset.ipynb
          - LJ potential: notebooks/Learn_LJ_potential.ipynb
plugins:
  - bibtex:
      bib_file: "docs/references.bib"
      cite_style: "pandoc"
  - mkdocs-jupyter
  - mkdocstrings:
      custom_templates: docs/templates
      handlers:
        python:
          rendering:
            show_source: true
            show_root_toc_entry: false
            heading_level: 4
            members: false
      watch:
        - pinn
  - mike
theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.png
  features:
    - navigation.sections
extra:
  version:
    provider: mike
markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - attr_list
  - footnotes
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.details
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - css/extra.css
