site_name: PiNN Documentation
nav:
  - Home:
    - Introduction: index.md
    - Cite PiNN: cite.md
  - Usage:
    - Overview: usage/overview.md
    - Datasests: usage/datasets.md
    - Networks:
      - Overview: usage/networks.md
      - Implemented:
        - PiNet: usage/pinet.md
        - BPNN: usage/bpnn.md
    - Models:
      - Overview: usage/models.md
      - Implemented:
        - Potential Model: usage/potential.md
        - Dipole Model: usage/dipole.md
      - Custom Mdoel: usage/custom_model.md
      - Optimizers: usage/optimizers.md
    - CLI: usage/cmd.md
    # - Ray Tune: usage/tune.md
    - Visualize: usage/visualize.md
  - Notebooks:
    - Overview: notebooks/overview.md
    - Tutorials:
      - Quick Start: notebooks/Quick_tour.ipynb
      - Training Tips: notebooks/More_on_training.ipynb
    - Examples:
      - Custom Dataset: notebooks/Customizing_dataset.ipynb
      - LJ potential: notebooks/Learn_LJ_potential.ipynb
      # - Hyperparameter Tuning: notebooks/Tune_visualize.ipynb
  # - API Reference:
  #   - pinn.layers: empty.md
  #   - pinn.networks: empty.md
  #   - pinn.models: empty.md
plugins:
  - bibtex:
      bib_file: "docs/references.bib"
      cite_style: "pandoc"
  - mkdocs-jupyter
  - mike
theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.png
  features:
    - navigation.sections
    - toc.integrate
extra:
  version:
    provider: mike
markdown_extensions:
  - toc:
      toc_depth: 1
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.superfences
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - css/extra.css
