site_name: <span>Pi</span>NN
repo_name: teoroo-cmc/pinn
repo_url: https://github.com/teoroo-cmc/pinn/
site_url: https://teoroo-cmc.github.io/pinn/
nav:
  - Home:
      - Introduction: index.md
      - Changelog: changelog.md
      - Migration: migration.md
  - Usage:
      - Overview: usage/overview.md
      - Quick Start: usage/quick_start.md
      - IO:
          - Datasets: usage/datasets.md
      - Networks:
          - Overview: usage/networks.md
          - PiNet: usage/pinet.md
          - BPNN: usage/bpnn.md
      - Models:
          - Overview: usage/models.md
          - Potential: usage/potential.md
          - Dipole: usage/dipole.md
          - Customize: usage/custom_model.md
      - CLI:
          - convert: usage/cli/convert.md
          - train: usage/cli/train.md
          - log: usage/cli/log.md
      - Misc:
          - Optimizers: usage/optimizers.md
          - Visualize: usage/visualize.md
  - Notebooks:
      - Overview: notebooks/overview.md
      - Tutorials:
          - Quick Start: notebooks/Quick_tour.ipynb
          - Training Tips: notebooks/More_on_training.ipynb
      - Examples:
          - Custom Data: notebooks/Customizing_dataset.ipynb
          - LJ Potential: notebooks/Learn_LJ_potential.ipynb
plugins:
  - bibtex:
      bib_file: "docs/references.bib"
      csl_file: "docs/jcp.csl"
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - mkdocstrings:
      custom_templates: docs/templates
      handlers:
        python:
          rendering:
            show_source: false
            show_root_toc_entry: false
            heading_level: 4
      watch:
        - pinn
  - mike
theme:
  name: flux
extra:
  version:
    provider: mike
markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - attr_list
  - footnotes
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.3/tex-chtml-nofont.js
extra_css:
  - css/extra.css
